#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"

save_relay_config() {
  local config_file="$1"
  local target_host="$2"
  local target_port="$3"
  local source_host="$4"
  local body_port="$5"
  mkdir -p "$(dirname -- "${config_file}")"
  {
    printf 'KITOV_XROBOT_RELAY_TARGET_HOST=%q\n' "${target_host}"
    printf 'KITOV_XROBOT_RELAY_TARGET_PORT=%q\n' "${target_port}"
    printf 'KITOV_BUMI_BODY_SOURCE_HOST=%q\n' "${source_host}"
    printf 'KITOV_BUMI_BODY_PORT=%q\n' "${body_port}"
  } >"${config_file}"
}

configure_x86_relay() {
  local config_file="${KITOV_XROBOT_RELAY_CONFIG:-${REPO_ROOT}/workspace/xrobot_relay.env}"
  local env_target_host="${KITOV_XROBOT_RELAY_TARGET_HOST-}"
  local env_target_port="${KITOV_XROBOT_RELAY_TARGET_PORT-}"
  local env_source_host="${KITOV_BUMI_BODY_SOURCE_HOST-}"
  local env_body_port="${KITOV_BUMI_BODY_PORT-}"
  local target_host="192.168.110.83"
  local target_port="47001"
  local source_host="192.168.110.84"
  local body_port="47001"
  local input_host input_port

  if [[ -f "${config_file}" ]]; then
    # This file is generated by this menu and contains only shell assignments.
    # shellcheck disable=SC1090
    source "${config_file}"
    target_host="${KITOV_XROBOT_RELAY_TARGET_HOST:-${target_host}}"
    target_port="${KITOV_XROBOT_RELAY_TARGET_PORT:-${target_port}}"
    source_host="${KITOV_BUMI_BODY_SOURCE_HOST:-${source_host}}"
    body_port="${KITOV_BUMI_BODY_PORT:-${body_port}}"
  fi
  [[ -n "${env_target_host}" ]] && target_host="${env_target_host}"
  [[ -n "${env_target_port}" ]] && target_port="${env_target_port}"
  [[ -n "${env_source_host}" ]] && source_host="${env_source_host}"
  [[ -n "${env_body_port}" ]] && body_port="${env_body_port}"

  printf '\nPICO -> BUMI UDP relay 配置:\n'
  printf '默认目标 IP：%s\n' "${target_host}"
  read -r -p "目标 IP（直接回车确认）：" input_host
  if [[ -n "${input_host}" ]]; then
    target_host="${input_host}"
  fi

  printf '默认目标端口：%s\n' "${target_port}"
  read -r -p "目标端口（直接回车确认）：" input_port
  if [[ -n "${input_port}" ]]; then
    target_port="${input_port}"
  fi

  if [[ -z "${target_host}" ]]; then
    echo '目标 IP 不能为空' >&2
    return 1
  fi
  if [[ ! "${target_port}" =~ ^[0-9]+$ ]] || ((target_port < 1 || target_port > 65535)); then
    echo "目标端口无效：${target_port}，必须是 1-65535" >&2
    return 1
  fi

  save_relay_config "${config_file}" "${target_host}" "${target_port}" "${source_host}" "${body_port}"
  echo "已保存 relay 配置：${config_file}"

  KITOV_XROBOT_RELAY_TARGET_HOST="${target_host}"
  KITOV_XROBOT_RELAY_TARGET_PORT="${target_port}"
  export KITOV_XROBOT_RELAY_TARGET_HOST KITOV_XROBOT_RELAY_TARGET_PORT
}

configure_bumi_udp() {
  local config_file="${KITOV_XROBOT_RELAY_CONFIG:-${REPO_ROOT}/workspace/xrobot_relay.env}"
  local env_source_host="${KITOV_BUMI_BODY_SOURCE_HOST-}"
  local env_body_port="${KITOV_BUMI_BODY_PORT-}"
  local env_target_host="${KITOV_XROBOT_RELAY_TARGET_HOST-}"
  local env_target_port="${KITOV_XROBOT_RELAY_TARGET_PORT-}"
  local target_host="192.168.110.83"
  local target_port="47001"
  local source_host="192.168.110.84"
  local body_port="47001"
  local input_host input_port

  if [[ -f "${config_file}" ]]; then
    # shellcheck disable=SC1090
    source "${config_file}"
    target_host="${KITOV_XROBOT_RELAY_TARGET_HOST:-${target_host}}"
    target_port="${KITOV_XROBOT_RELAY_TARGET_PORT:-${target_port}}"
    source_host="${KITOV_BUMI_BODY_SOURCE_HOST:-${source_host}}"
    body_port="${KITOV_BUMI_BODY_PORT:-${body_port}}"
  fi
  [[ -n "${env_source_host}" ]] && source_host="${env_source_host}"
  [[ -n "${env_body_port}" ]] && body_port="${env_body_port}"
  [[ -n "${env_target_host}" ]] && target_host="${env_target_host}"
  [[ -n "${env_target_port}" ]] && target_port="${env_target_port}"

  printf '\nUDP 接收配置:\n'
  printf '默认 x86 源 IP：%s\n' "${source_host}"
  read -r -p "x86 源 IP（直接回车确认）：" input_host
  if [[ -n "${input_host}" ]]; then
    source_host="${input_host}"
  fi

  printf '默认监听端口：%s\n' "${body_port}"
  read -r -p "监听端口（直接回车确认）：" input_port
  if [[ -n "${input_port}" ]]; then
    body_port="${input_port}"
  fi

  if [[ -z "${source_host}" ]]; then
    echo 'x86 源 IP 不能为空' >&2
    return 1
  fi
  if [[ ! "${body_port}" =~ ^[0-9]+$ ]] || ((body_port < 1 || body_port > 65535)); then
    echo "监听端口无效：${body_port}，必须是 1-65535" >&2
    return 1
  fi

  save_relay_config "${config_file}" "${target_host}" "${target_port}" "${source_host}" "${body_port}"
  echo "已保存 UDP 配置：${config_file}"
  KITOV_BUMI_BODY_SOURCE_HOST="${source_host}"
  KITOV_BUMI_BODY_PORT="${body_port}"
  export KITOV_BUMI_BODY_SOURCE_HOST KITOV_BUMI_BODY_PORT
}

run_g1() {
  exec "${SCRIPT_DIR}/g1/run_g1_policy_sim.sh" "$@"
}

run_bumi_real() {
  printf '\nBUMI RGMT 真机端:\n'
  printf '  1) x86 端：PICO -> UDP relay\n'
  printf '  2) BUMI 端：UDP -> GMR -> RGMT -> Noetix\n'
  printf '  q) 返回\n'
  read -r -p '请选择 [1-2/q]: ' choice
  case "${choice}" in
    1)
      configure_x86_relay || return 1
      exec "${SCRIPT_DIR}/relay/run_xrobot_frame_relay.sh" "$@"
      ;;
    2)
      configure_bumi_udp || return 1
      KITOV_BUMI_BODY_SOURCE=udp exec "${SCRIPT_DIR}/bumi/run_bumi_policy_real.sh" "$@"
      ;;
    q|Q) return 0 ;;
    *) echo '无效选择' >&2; return 1 ;;
  esac
}

run_bumi() {
  printf '\nBUMI 模式:\n'
  printf '  1) BFM policy MuJoCo 仿真\n'
  printf '  2) RGMT MuJoCo 仿真\n'
  printf '  3) RGMT 真机\n'
  printf '  q) 返回\n'
  read -r -p '请选择 [1-3/q]: ' choice
  case "${choice}" in
    1) exec "${SCRIPT_DIR}/bumi/run_bumi_policy_sim.sh" "$@" ;;
    2) exec "${SCRIPT_DIR}/bumi/run_bumi_rgmt_policy_sim.sh" "$@" ;;
    3) run_bumi_real "$@" ;;
    q|Q) return 0 ;;
    *) echo '无效选择' >&2; return 1 ;;
  esac
}

run_openarm() {
  exec "${SCRIPT_DIR}/openarm/run_openarm_teleop.sh" "$@"
}

if [[ "$#" -gt 0 ]]; then
  case "$1" in
    g1) shift; run_g1 "$@" ;;
    bumi) shift; run_bumi "$@" ;;
    openarm) shift; run_openarm "$@" ;;
    *)
      echo "用法: $0 [g1|bumi|openarm] [额外参数...]" >&2
      exit 2
      ;;
  esac
fi

while true; do
  printf '\nKitov 启动器\n'
  printf '  1) G1 policy MuJoCo 仿真\n'
  printf '  2) BUMI\n'
  printf '  3) OpenArm v1 实时遥操作\n'
  printf '  q) 退出\n'
  read -r -p '请选择 [1-3/q]: ' choice
  case "${choice}" in
    1) run_g1 ;;
    2) run_bumi ;;
    3) run_openarm ;;
    q|Q) exit 0 ;;
    *) echo '无效选择' >&2 ;;
  esac
done
