#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../../.." && pwd)"
cd "${REPO_ROOT}"

RELAY_CONFIG="${KITOV_XROBOT_RELAY_CONFIG:-${REPO_ROOT}/workspace/xrobot_relay.env}"
ENV_TARGET_HOST="${KITOV_XROBOT_RELAY_TARGET_HOST-}"
ENV_TARGET_PORT="${KITOV_XROBOT_RELAY_TARGET_PORT-}"
if [[ -f "${RELAY_CONFIG}" ]]; then
  # This file is generated by scripts/launch/launch.sh.
  # shellcheck disable=SC1090
  source "${RELAY_CONFIG}"
  [[ -n "${ENV_TARGET_HOST}" ]] && KITOV_XROBOT_RELAY_TARGET_HOST="${ENV_TARGET_HOST}"
  [[ -n "${ENV_TARGET_PORT}" ]] && KITOV_XROBOT_RELAY_TARGET_PORT="${ENV_TARGET_PORT}"
fi

TARGET_HOST="${KITOV_XROBOT_RELAY_TARGET_HOST:-192.168.110.83}"
TARGET_PORT="${KITOV_XROBOT_RELAY_TARGET_PORT:-47001}"
HZ="${KITOV_XROBOT_RELAY_HZ:-72}"
SERVICE_SCRIPT="${KITOV_XROBOT_SERVICE_SCRIPT:-/opt/apps/roboticsservice/runService.sh}"
SERVICE_PATTERN="${KITOV_XROBOT_SERVICE_PATTERN:-[R]oboticsServiceProcess}"
STOP_SERVICE_ON_EXIT="${KITOV_STOP_ROBOTICS_SERVICE_ON_EXIT:-1}"
SERVICE_SHOULD_STOP=0

cleanup() {
  local status=$?
  trap - INT TERM EXIT
  if [[ "${STOP_SERVICE_ON_EXIT}" != "0" && "${SERVICE_SHOULD_STOP}" == "1" ]]; then
    if pgrep -f "${SERVICE_PATTERN}" >/dev/null 2>&1; then
      echo "[run_xrobot_frame_relay] stopping XRoboToolkit PC Service"
      pkill -f "${SERVICE_PATTERN}" 2>/dev/null || true
    fi
  fi
  exit "${status}"
}
trap cleanup INT TERM EXIT

if ! pgrep -f "${SERVICE_PATTERN}" >/dev/null 2>&1; then
  if [[ ! -x "${SERVICE_SCRIPT}" ]]; then
    echo "[run_xrobot_frame_relay] service script not found or not executable: ${SERVICE_SCRIPT}" >&2
    exit 1
  fi
  echo "[run_xrobot_frame_relay] starting XRoboToolkit PC Service"
  "${SERVICE_SCRIPT}"
  sleep 1
  if ! pgrep -f "${SERVICE_PATTERN}" >/dev/null 2>&1; then
    echo "[run_xrobot_frame_relay] XRoboToolkit PC Service did not start" >&2
    exit 1
  fi
  SERVICE_SHOULD_STOP=1
fi

set +e
uv run python "${REPO_ROOT}/scripts/launch/relay/xrobot_frame_relay.py" \
  --target-host "${TARGET_HOST}" \
  --target-port "${TARGET_PORT}" \
  --hz "${HZ}" \
  "$@"
STATUS=$?
set -e
exit "${STATUS}"
